# -*- coding: utf-8 -*-
"""alignment.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PmEWbjY_S0q32rYyoUCBWJIIpkmrX6U7
"""

# alignment.py

import numpy as np
import time

def ssd(img1, img2):
    """Sum of Squared Differences (SSD)"""
    return np.sum((img1 - img2)**2)

def ncc(img1, img2):
    """Normalized Cross-Correlation (NCC)"""
    img1_mean = img1 - np.mean(img1)
    img2_mean = img2 - np.mean(img2)
    return np.sum(img1_mean * img2_mean) / np.sqrt(np.sum(img1_mean**2) * np.sum(img2_mean**2))

def align_channel(base, channel, max_shift=15, metric='ssd'):
    """Bir kanalı referans kanala hizalar"""
    print(f"\n--- Kanal hizalama başladı ({metric.upper()} metrik kullanılıyor) ---")
    start_time = time.time()

    h, w = base.shape
    crop = 0.1
    h_crop = int(h * crop)
    w_crop = int(w * crop)
    base_cropped = base[h_crop:h-h_crop, w_crop:w-w_crop]
    channel_cropped = channel[h_crop:h-h_crop, w_crop:w-w_crop]

    best_score = None
    best_shift = (0, 0)

    for dx in range(-max_shift, max_shift + 1):
        for dy in range(-max_shift, max_shift + 1):
            shifted = np.roll(channel_cropped, shift=(dx, dy), axis=(0, 1))
            if metric == 'ssd':
                score = ssd(base_cropped, shifted)
                if best_score is None or score < best_score:
                    best_score = score
                    best_shift = (dx, dy)
            elif metric == 'ncc':
                score = ncc(base_cropped, shifted)
                if best_score is None or score > best_score:
                    best_score = score
                    best_shift = (dx, dy)

    aligned_channel = np.roll(channel, shift=best_shift, axis=(0, 1))
    elapsed_time = time.time() - start_time
    print(f"Hizalama tamamlandı. En iyi kaydırma: {best_shift}, süre: {elapsed_time:.2f} sn")

    return aligned_channel, best_shift