# -*- coding: utf-8 -*-
"""enhancement.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G-TuJshklQWf5zGeW789DB3b3tnXUimF
"""

# enhancement.py

from skimage import exposure
import numpy as np
import matplotlib.pyplot as plt

def crop_edges(img, crop_ratio=0.10):
    """Kenarları kırpar"""
    print(f"\n[Kırpma] Görüntü kenarlarının %{int(crop_ratio*100)}'i kırpılıyor...")
    h, w, _ = img.shape
    h_crop = int(h * crop_ratio)
    w_crop = int(w * crop_ratio)
    return img[h_crop:h-h_crop, w_crop:w-w_crop]

def normalize(img):
    """Piksel değerlerini 0-1 aralığına normalize eder"""
    print("[Normalize] Piksel değerleri 0-1 aralığına çekiliyor...")
    return (img - np.min(img)) / (np.max(img) - np.min(img))

def hist_equalize(img):
    """Histogram eşitleme (her kanal ayrı)"""
    print("[Histogram Eşitleme] Her kanal için ayrı eşitleme uygulanıyor...")
    out = np.zeros_like(img)
    for i in range(3):
        out[:,:,i] = exposure.equalize_hist(img[:,:,i])
    return out

def gamma_correction(img, gamma=1.2):
    """Gama düzeltme ile parlaklığı ayarlar"""
    print(f"[Gamma Düzeltme] Gamma katsayısı: {gamma}")
    return img ** gamma

def auto_crop_black(img, threshold=0.10):
    """Siyah kenarları otomatik kırpar"""
    print("[Siyah Kırpma] Kenarlardaki siyah bölgeler tespit ediliyor...")
    mask = np.max(img, axis=2) > threshold
    rows = np.any(mask, axis=1)
    cols = np.any(mask, axis=0)
    rmin, rmax = np.where(rows)[0][[0, -1]]
    cmin, cmax = np.where(cols)[0][[0, -1]]
    print(f"[Siyah Kırpma] Kesilen alan: satırlar({rmin}-{rmax}), sütunlar({cmin}-{cmax})")
    return img[rmin:rmax+1, cmin:cmax+1]

def enhance_image(color_image):
    """Tüm iyileştirme adımlarını sırasıyla uygular"""
    print("\n--- Görüntü İyileştirme Başladı ---")

    color_cropped = crop_edges(color_image)
    color_norm = normalize(color_cropped)
    color_hist = hist_equalize(color_norm)
    color_gamma = gamma_correction(color_hist, gamma=1.2)
    final_img = auto_crop_black(color_gamma)

    print("[Tamamlandı] Görüntü iyileştirme pipeline'ı başarıyla tamamlandı.")
    return final_img