# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V4b-B5RjwUsPA_62_ZeehRmk73aPaDl4
"""

from google.colab import files
from skimage import io, img_as_float, exposure
import matplotlib.pyplot as plt
import numpy as np

print("Lütfen 3 kanallı (B, G, R sıralı)")
uploaded = files.upload()
filename = list(uploaded.keys())[0]

# Görüntüyü yükle
image = img_as_float(io.imread(filename))
print("", image.shape)

# Üç eşit parçaya böl (B, G, R)
height = image.shape[0] // 3
B = image[0:height, :]
G = image[height:2*height, :]
R = image[2*height:3*height, :]

# Kanalları göster
fig, ax = plt.subplots(1, 3, figsize=(12,8))
ax[0].imshow(B, cmap='gray'); ax[0].set_title("Blue Kanalı")
ax[1].imshow(G, cmap='gray'); ax[1].set_title("Green Kanalı")
ax[2].imshow(R, cmap='gray'); ax[2].set_title("Red Kanalı")
for a in ax: a.axis("off")
plt.show()

G_aligned, shift_G = align_channel(B, G, max_shift=15, metric='ssd')
R_aligned, shift_R = align_channel(B, R, max_shift=15, metric='ssd')

print("Green kaydırma:", shift_G)
print("Red kaydırma:", shift_R)

# Hizalanmış kanalları birleştir (RGB)
color_image = np.dstack([R_aligned, G_aligned, B])

# Sonuç göster
plt.figure(figsize=(6,4))
plt.imshow(np.clip(color_image,0,1))
plt.axis("off")
plt.title("Hizalanmış Renkli Görüntü")
plt.show()

fig, axes = plt.subplots(1,3, figsize=(12,8))
axes[0].imshow(np.clip(np.dstack([R,G,B]),0,1))
axes[0].set_title("Orijinal Hizalanmamış")
axes[1].imshow(np.clip(color_image,0,1))
axes[1].set_title("Hizalanmış")
axes[2].imshow(np.clip(final_img,0,1))
axes[2].set_title("İyileştirilmiş Final")
for ax in axes:
    ax.axis("off")
plt.show()